### ISSUE TITLE
Assignment2 Issues

### ISSUE THREAD

**Issue by wesleysfng** [IntroToCode/CodeMates3_Spring23#1]
## 💬 Discussion topic

Text

## ❗ Potential issues

Text

## 👥 People to consult

@josephyuberkeley 
@cheriekwok 
@wesleysfng 
@kichimori 
@craig-kc 

## 📃 Details

Text

**Comment by josephyuberkeley** [comment]
Awesome! Let's choose a recipe for dinner and breakfast!! 🍽️
