### ISSUE TITLE
Need ALL to commit to both recipes in the Group-Branch-1 for a pull request to get full credit

### ISSUE THREAD

**Issue by josephyuberkeley** [IntroToCode/CodeMates3_Spring23#10]
## 💬 Discussion topic

Need ALL to commit to both recipes in the Group-Branch-1 for a pull request to get full credit

## ❗ Potential issues

We all need to have a COMMIT on BOTH dinner and breakfast recipes. ONE person can then generate a pull request for the approval and merge. We have already created a new branch that we can all work on: it is **group-branch-1**  Cherie and I have already added our commits to the dinner recipe. 
Please comment if you have any follow up questions

## 👥 People to consult

@wesleysfng 
@kichimori 
@cheriekwok 
@korawatt 
@craig-kc 
@josephyuberkeley 

## 📃 Details

Text

**Comment by cheriekwok** [comment]
Remember not to complete the pull request until **all ** members of the group have made their edits! So whoever is last can merge it.

**Comment by josephyuberkeley** [comment]
<img width="724" alt="image" src="https://user-images.githubusercontent.com/125529280/222338576-a0b0ba29-f102-44cf-8c23-8dbf37c0da13.png">

**Comment by wesleysfng** [comment]
Ok thanks for catching this! Will add my commit

**Comment by wesleysfng** [comment]
Added my commit to breakfast on group-branch-1

**Comment by josephyuberkeley** [comment]
Just a reminder for @kichimori to also add a commit to the dinner recipe
and for @korawatt and @craig-kc to add a commit to the breakfast recipe

**Comment by kichimori** [comment]
Thanks, Joe! I added my commit

**Comment by craig-kc** [comment]
Thanks Joe. @wesleysfng @korawatt I performed two tasks that need approval comments and then ultimately merged. I updated the Dinner 'readme' file name to 'FrenchToast' and then I created a new branch and make a commit to add a spatula. Can you add some comments for approval and then I can do a pull request.

**Comment by wesleysfng** [comment]
Hi @craig-kc, I think you made the edit commits to the main branch instead of group-branch-1? I think we're going to add commits to the group-branch-1 and then make a pull request to merge the group-branch-1 with the main-branch

**Comment by craig-kc** [comment]
Hey @wesleysfng I made a new branch Kevin's_Enhancements_branch. Are all 6 of us working off group-branch-1? If so that's cool I just made a commit to group-branch-1 and can delete the Kevin's_Enhancements_branch. Just let me know.

**Comment by wesleysfng** [comment]
I think so @craig-kc ?  @josephyuberkeley @cheriekwok  I believe we're trying to have all the commits on group-branch-1 before we make 1 big pull request to main branch right?

**Comment by craig-kc** [comment]
I think you are correct @wesleysfng, that's what @josephyuberkeley mentioned in his first post so my bad. I made my commit to group-branch-1 and deleted the other branch I created. Made some comments on some of the other commits too.

**Comment by korawatt** [comment]
Am I right that everything is great for the dinner branch? Thanks to @josephyuberkeley for your good point.

**Comment by josephyuberkeley** [comment]
Hi @wesleysfng, @craig-kc, @korawatt!
Yes, the missing item is that EVERYONE needs to commit on BOTH dinner and breakfast recipes. Since we originally divided and conquered with @cheriekwok, @kichimori and myself working on the breakfast recipe (breakfast.md file) and @wesleysfng @craig-kc @korawatt on the dinner recipe (dinner.md file). We all just need to commit on the recipe which we didn't originally commit on.
As far as execution goes, it's easier if everyone commits on the "group-branch-1" that way we only need to have one pull-request to merge into main.

**Comment by josephyuberkeley** [comment]
Hi all, 
@cheriekwok @wesleysfng @kichimori @craig-kc @korawatt 
Just checked the commits on "group-branch-1", looks like we're just missing @korawatt to commit on the breakfast file. 
@korawatt, to do so, click on "code" -> "branches" ->  "group-branch-1" -> "breakfast" file -> edit button on the right -> make your edits in the recipe -> "commit changes" at the bottom.

@korawatt , let me know when you have your commits in the branch and we can start a pull-request to merge to main. Thanks!

**Comment by korawatt** [comment]
@josephyuberkeley I just committed my change. Kindly help audit whether I did the right one. Sorry if I missed this and thanks for your patience.

**Comment by josephyuberkeley** [comment]
Hi @korawatt , thanks for the quick response! I don't see the commit yet. Looks like the last commit was from Craig-KC 6 hours ago. 

<img width="1217" alt="image" src="https://user-images.githubusercontent.com/125529280/223050152-3bf08d8b-a5ba-4001-8201-40c44f7adbf7.png">

**Comment by korawatt** [comment]
Am I doing the right one for this?

![image](https://user-images.githubusercontent.com/125529111/223050735-b6d47e17-7e69-4bd9-8422-c2b48cc31be0.png)

**Comment by josephyuberkeley** [comment]
@korawatt 
that looks right, but for some reason I'm not seeing it. Let me login and logout. This is what I'm seeing on my end.

<img width="994" alt="image" src="https://user-images.githubusercontent.com/125529280/223051440-0b26fb27-3956-4c21-bc13-e02800071201.png">

**Comment by josephyuberkeley** [comment]
@korawatt, I think you may have created a side branch called patch-3 from the group-branch-1. (see network diagram below). I think this is fine too. It also looks like you've started a pull-request with patch-3, you'll just need to add TWO approvers to the pull-request to comply with the Prof's guidelines.

<img width="654" alt="image" src="https://user-images.githubusercontent.com/125529280/223052570-3af5eb56-1e48-4c9d-b973-90ffd5c67a49.png">

**Comment by josephyuberkeley** [comment]
@korawatt, also be sure to update the "breakfast.md" file rather than the "readme" file. Let me know if you need help, but here's a quick step-by-step.

click on "code" -> "branches" -> "group-branch-1" -> "breakfast" file -> edit button on the right -> make your edits in the recipe -> "commit changes" at the bottom.

**Comment by wesleysfng** [comment]
Hi Team, with Korawat right now - seems like @korawatt isn't part of our team group and so can't submit direct commits to the group-branch-1 and can only submit patch pull request. I think we should just approve his patch-3 and then later we can pull request group-branch-1 to the main branch.

**Comment by josephyuberkeley** [comment]
@wesleysfng and @korawatt, got it! Yes, let's get both pull requests going so that they both merge into main. Just need to make sure we have at least TWO approvers on each pull request. I'm happy to get the pull requests started!

**Comment by josephyuberkeley** [comment]
@wesleysfng and @cheriekwok, I started a pull-request for "group-branch-1". Could the both of you help with approving the pull-request with the last person merging to main? Thanks in advance!

Here's a summary of the 8 commits from all 6 of us in this pull-request.

<img width="853" alt="image" src="https://user-images.githubusercontent.com/125529280/223275923-7c4e3699-9fc5-48c2-b6e9-2cf0ae656caa.png">

**Comment by cheriekwok** [comment]
Approved & merged!

**Comment by josephyuberkeley** [comment]
Awesome! Thanks so much for merging us back to Main! Closing this issue!

<img width="553" alt="image" src="https://user-images.githubusercontent.com/125529280/223499122-954227a6-e71c-4bc9-94c3-9babf185d66e.png">
