### ISSUE TITLE
Divide and conquer

### ISSUE THREAD

**Issue by cheriekwok** [IntroToCode/CodeMates3_Spring23#2]
## 💬 Discussion topic

3 people will take each meal
Meal chosen by subgroup

## ❗ Potential issues

Recipe disagreements to be decided by consensus

## 👥 People to consult

@kichimori @craig-kc @wesleysfng @josephyuberkeley @korawatt

## 📃 Details

Pick 2 teams and divide into ingredients and recipe:
Breakast:
@kichimori 
@josephyuberkeley 
@cheriekwok 

Dinner:
@wesleysfng 
@craig-kc 
@korawatt

**Comment by wesleysfng** [comment]
Sounds good!

**Comment by josephyuberkeley** [comment]
Looks good!

**Comment by josephyuberkeley** [comment]
All commits and branches have been merged
